---
name: ETLSentiment
version: 1
debug: true
hard-terminate-time: 2
cache:
  expire-in: 1
  max-size: 1000
messenger:
  logging:
    directory: ''
  enable-logging: true
  smtp:
    endpoint:
      host: smtp.gmail.com
      port: '587'
    credentials:
      email: etlautomated@gmail.com
      password: ''
    subscribers:
      from-reddit:
      - gabecofficial@gmail.com
  enable-smtp: false
net:
  host: 0.0.0.0
  port: 8136
Path: ''