name: Go Checkers
on:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  gocoverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [production, debug, development]
    env:
      GOPRIVATE: github.com/FortifiedCode
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1' # The Go version to download (if necessary) and use.
      - run: go version
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: check test coverage
        run: go test ./... -covermode=atomic -coverpkg=./... -tags ${{ matrix.tag }}
  gorace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ production, debug, development ]
    env:
      GOPRIVATE: github.com/FortifiedCode
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1' # The Go version to download (if necessary) and use.
      - run: go version
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: check test coverage
        run: go test ./... -race -covermode=atomic -coverpkg=./... -tags ${{ matrix.tag }}
  gosec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ production, debug, development ]
    env:
      GO111MODULE: on
      GOPRIVATE: github.com/FortifiedCode
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: install gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.22.8
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: check security vulnerabilities
        run: /home/runner/go/bin/gosec ./... -tags ${{ matrix.tag }}