name: Go Checkers
on:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  gocoverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1' # The Go version to download (if necessary) and use.
      - run: go version
      - name: check test coverage
        run: go test ./... -covermode=atomic -coverpkg=./...
  gorace:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1' # The Go version to download (if necessary) and use.
      - run: go version
      - name: check test coverage
        run: go test ./... -race -covermode=atomic -coverpkg=./...
